### ISSUE TITLE
Fix color in `remote read` removing the GREEN

### ISSUE THREAD

**Issue by mas2020** [mas2020-golang/goal-modules#17]
Leave the `read` sub command as:
```yaml
  - name: read
    usage: read <file>
    alias: rd
    args: ">=1"
    shortDesc: read a file and show the content
    description: |
      Read a file and show the content on the standard output
      goal read /tmp/file
      goal read /tmp/file

      Remote command used is 'more'
    category: files
    systems:
      - type: "*"
        cmd: |
          more
```
